name: zego_zimkit_demo
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  zego_zimkit:
    git:
      url: https://github.com/ZEGOCLOUD/beta_version
      path: zego_zimkit
      ref: ghbeta

  zego_uikit_prebuilt_call:
    git:
      url: https://github.com/ZEGOCLOUD/beta_version
      path: zego_uikit_prebuilt_call
      ref: ghbeta

  zego_uikit_signaling_plugin: 
    git:
      url: https://github.com/ZEGOCLOUD/beta_version
      path: zego_uikit_signaling_plugin
      ref: ghbeta


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  dart_code_metrics: any
  import_sorter: any

import_sorter:
  comments: false

flutter:
  uses-material-design: true
