name: zego_uikit_prebuilt_video_conference
description: PrebuiltVideoConference is a full-featured Video Conference kit that provides a ready-made group voice/video chat, in-room message, dynamic layout, member list, etc.
version: 1.1.12
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_video_conference_flutter
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_screenutil: ^5.5.3+2
  zego_uikit: 
    git:
      url: https://github.com/ZEGOCLOUD/beta_version
      path: zego_uikit
      ref: ghbeta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any

flutter:
  assets:
    - assets/icons/
